# why.toml - Example Configuration File

[audio.capture]
enabled = true
sample_rate = 48000
channels = 2
ring_frames = 8192
device = ""
input_gain = 1.0
system = false

[audio.file]
enabled = false
path = ""
channels = 1
gain = 1.0

[audio]
prefer_file = false

[dsp]
fft_size = 1024
hop_size = 256
bands = 32
window = "hann"
smoothing_attack = 0.2
smoothing_release = 0.05
beat_sensitivity = 1.0
enable_flux = true

[visual]
target_fps = 60.0

[runtime]
show_metrics = true
allow_resize = true
beat_flash = true
show_overlay_metrics = true

[plugins]
directory = "plugins"
autoload = ["beat-flash-debug"]
safe_mode = false

[[animations]]
type = "RandomText"
z_index = 0
initially_active = false
trigger_beat_min = 0.1 # Activate when beat strength is above 0.1
text_file_path = "assets/dune.txt"
trigger_cooldown_s = 1.0 # Increased cooldown
type_speed_words_per_s = 15.0
display_duration_s = 1.0 # Longer display duration
fade_duration_s = 1.0 # Longer fade duration
max_active_lines = 3 # Fewer active lines for better centering

[[animations]]
type = "BarVisual"
z_index = 1
initially_active = false
trigger_band_index = 0 # Trigger on the first frequency band
trigger_threshold = 0.001 # Activate when energy in band 0 is above 0.001
text_file_path = "assets/bar.txt"
plane_y = 0
plane_x = 0
plane_rows = 10
plane_cols = 100

[[animations]]
type = "AsciiMatrix"
z_index = 2
initially_active = true
glyphs_file_path = "assets/ascii_matrix.txt"
matrix_rows = 12
matrix_cols = 40
matrix_show_border = true
matrix_beat_boost = 2.0
matrix_beat_threshold = 0.55
plane_y = 40
plane_x = 10
