# why.toml - Example Configuration File

[audio.capture]
enabled = true
sample_rate = 48000
channels = 2
ring_frames = 8192
device = ""
input_gain = 1.0
system = false

[audio.file]
enabled = false
path = ""
channels = 1
gain = 1.0

[audio]
prefer_file = false

[dsp]
fft_size = 1024
hop_size = 256
bands = 32
window = "hann"
smoothing_attack = 0.2
smoothing_release = 0.05
beat_sensitivity = 1.0
enable_flux = true

[visual]
target_fps = 60.0

[runtime]
show_metrics = true
allow_resize = true
beat_flash = true
show_overlay_metrics = true

[plugins]
directory = "plugins"
autoload = ["beat-flash-debug"]
safe_mode = false

[[animations]]
type = "RandomText"
z_index = 0

[[animations]]
type = "BarVisual"
z_index = 1

[[animations]]
type = "StaticCircle"
z_index = 2