# why.toml - Example Configuration File

[audio.capture]
enabled = true
sample_rate = 48000
channels = 2
ring_frames = 8192
device = ""
input_gain = 1.0
system = false

[audio.file]
enabled = false
path = ""
channels = 1
gain = 1.0

[audio]
prefer_file = false

[dsp]
fft_size = 1024
hop_size = 256
bands = 32
window = "hann"
smoothing_attack = 0.2
smoothing_release = 0.05
beat_sensitivity = 1.0
enable_flux = true

[visual]
target_fps = 60.0

[runtime]
show_metrics = true
allow_resize = true
beat_flash = true
show_overlay_metrics = true

[plugins]
directory = "plugins"
autoload = ["beat-flash-debug"]
safe_mode = false

[[animations]]
type = "RandomText"
z_index = 0
initially_active = false
trigger_beat_min = 0.1 # Activate when beat strength is above 0.1
text_file_path = "assets/dune.txt"
trigger_cooldown_s = 1.0 # Increased cooldown
type_speed_words_per_s = 30.0
display_duration_s = 1.0 # Longer display duration
fade_duration_s = 1.0 # Longer fade duration
max_active_lines = 3 # Fewer active lines for better centering
random_text_min_y_ratio = 0.4
random_text_max_y_ratio = 0.6

[[animations]]
type = "BarVisual"
z_index = 1
initially_active = false
trigger_band_index = 0 # Trigger on the first frequency band
trigger_threshold = 0.001 # Activate when energy in band 0 is above 0.001
text_file_path = "assets/bar.txt"
plane_y = 1
plane_x = 10
plane_rows = 10
plane_cols = 100

[[animations]]
type = "AsciiMatrix"
z_index = 2
initially_active = true
glyphs_file_path = "assets/ascii_matrix.txt"
matrix_rows = 12
matrix_cols = 40
matrix_show_border = true
matrix_beat_boost = 2.0
matrix_beat_threshold = 0.55
plane_y = 20
plane_x = 10

[[animations]]
type = "Logging"
z_index = 2
initially_active = true
text_file_path = "assets/logging_animation.txt"
plane_rows = 32
plane_cols = 32
plane_y = 4
plane_x = 120
log_line_interval_s = 0.5
log_loop_messages = true
log_show_border = true
log_padding_y = 1
log_padding_x = 2
log_title = "why::log"

[[animations]]
type = "CyberRain"
z_index = 0
initially_active = true
trigger_band_index = 15 # Focus on higher frequencies from the FFT bands
trigger_threshold = 0.001
glyphs_file_path = "assets/cyber_rain.txt"
type_speed_words_per_s = 16.0 # Controls the base scan speed across the plane
trigger_cooldown_s = 1.2 # Controls the scan speed boost when the effect triggers
display_duration_s = 0.75 # Persistence duration for the rain trails
fade_duration_s = 1.1
plane_y = 0
plane_x = 0
rain_angle_degrees = 25.0

[[animations]]
type = "LightningWave"
z_index = 3
initially_active = false
trigger_band_index = 20 # Focus on upper-mid frequencies for lightning riff detection
trigger_threshold = 0.001
glyphs_file_path = "assets/lightning_wave.txt"
display_duration_s = 0.8
fade_duration_s = 1.4
wave_speed_cols_per_s = 48.0
wave_front_width_cols = 3
wave_tail_length_cols = 8
wave_alternate_direction = true
wave_direction_right = true
trigger_cooldown_s = 0.2
# Lightning detection tuned for instrument novelty sweeps
lightning_novelty_threshold = 0.28
lightning_energy_floor = 0.01
lightning_detection_cooldown_s = 0.75
lightning_novelty_smoothing_s = 0.22
lightning_activation_decay_s = 0.9
plane_y = 0
plane_x = 0

[[animations]]
type = "Breathe"
z_index = 2
initially_active = true
glyphs_file_path = "assets/breathe_animation.txt"
display_duration_s = 0.9
fade_duration_s = 1.4
breathe_points = 72
breathe_min_radius = 6.0
breathe_max_radius = 18.0
breathe_audio_radius_influence = 12.0
breathe_smoothing_s = 0.16
breathe_noise_amount = 0.35
breathe_rotation_speed = 0.28
breathe_vertical_scale = 0.55
breathe_base_pulse_hz = 0.35
breathe_audio_pulse_weight = 0.85
breathe_band_index = 12
breathe_rms_weight = 1.0
breathe_beat_weight = 0.7
breathe_band_weight = 0.6
